[minecraft]
minecraft_server ansible_host=54.209.203.2 ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/cs312-key.pem

[minecraft:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
