name: Build and Push Minecraft Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
          aws configure set region us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: docker build -t cs312-minecraft .

      - name: Tag image
        run: |
          docker tag cs312-minecraft:latest \
            ${{ secrets.ECR_REGISTRY }}/cs312-minecraft:latest

      - name: Push image
        run: |
          docker push ${{ secrets.ECR_REGISTRY }}/cs312-minecraft:latest
